spring:
  datasource:
    url: jdbc:sqlserver://employeedatadb.database.windows.net:1433;database=employeedb;user=prama02@employeedatadb;password=Pakru@993;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: prama02
    password: Pakru@993
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      
server:
  port: 9192